version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sonic_ai_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - BASE_URL=http://3.219.30.218:8000
      - FRONTEND_URL=http://3.219.30.218:3000
    # environment:
    #   - MONGODB_URL=mongodb+srv://... (Or use local mongo container)
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://3.219.30.218:8000/api/v1
    container_name: sonic_ai_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://3.219.30.218:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
